name: gift
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311hc58e375_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - icu=75.1=hfee45f7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libcxx=21.1.4=hf598326_2
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libiconv=1.16=h80987f9_3
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=h4237e3c_0
  - libzlib=1.3.1=h8359307_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.2=py311h5bb9006_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h18782d2_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pyzmq=27.1.0=py311h13abfa4_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.4=hb5dd463_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.2=py311h3696347_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - pip:
      - adagio==0.2.6
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - antropy==0.1.9
      - anyio==4.11.0
      - arch==8.0.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.2.1
      - cloudpickle==3.1.1
      - contourpy==1.3.3
      - coreforecast==0.0.16
      - cycler==0.12.1
      - datasets==2.17.1
      - datasetsforecast==0.0.8
      - defusedxml==0.7.1
      - dill==0.3.8
      - dotenv==0.9.9
      - einops==0.7.0
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2023.10.0
      - fugue==0.9.1
      - gluonts==0.15.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.0.1
      - hydra-core==1.3.0
      - idna==3.11
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lightgbm==4.5.0
      - llvmlite==0.45.1
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mistune==3.1.4
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.62.1
      - numpy==1.26.4
      - omegaconf==2.3.0
      - orjson==3.11.4
      - overrides==7.7.0
      - pandas==2.0.0
      - pandocfilters==1.5.1
      - patsy==1.0.2
      - pillow==12.0.0
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - protobuf==6.33.0
      - pyarrow==22.0.0
      - pyarrow-hotfix==0.7
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyparsing==3.2.5
      - python-dotenv==1.0.0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - ray==2.51.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - scikit-learn==1.7.2
      - scipy==1.11.4
      - send2trash==1.8.3
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soupsieve==2.8
      - statsforecast==1.7.8
      - statsmodels==0.14.5
      - supersmoother==0.4
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - toolz==0.12.1
      - tqdm==4.67.1
      - triad==1.0.0
      - tsfeatures==0.4.5
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ujson==5.11.0
      - uri-template==1.3.0
      - urllib3==2.5.0
      - utilsforecast==0.2.11
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.14
      - xgboost==2.1.3
      - xlrd==2.0.2
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /opt/anaconda3/envs/gift
